#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

green=`tput setaf 2`
yellow=`tput setaf 3`
reset=`tput sgr0`

echo "${yellow}[linter] start to fix all"
eslint --fix
eslint "**/*.js" --ignore-pattern "node_modules/"
echo "${green}[linter] linter passed all project${reset}"