#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

red=`tput setaf 1`
green=`tput setaf 2`
reset=`tput sgr0`

echo "[linter] start to fix all"
eslint --fix
eslint "**/*.js" --ignore-pattern "node_modules/"
echo "${green} [linter] linter passed all project${reset}"